###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"rahul111",
    "username":"rahul111213",
    "password": "rahul@451611",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"rahul111213",
    "password": "rahul@451611"
}