###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"rahul11",
    "username":"rahul11213",
    "password": "rahul@45161",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"rahul123",
    "password": "rahul@456"
}